### ISSUE TITLE
Delete Report is not working 

### ISSUE THREAD

**Issue by sambitdixit** [rakam-io/rakam-ui#67]
I created a report and then came back tried to delete the report. It shows report does not exist. 

If a report created by other is visible to me and since I'm having write, read, admin privilege i tried to delete the report. Its showing report does not exist.  This is a critical functionality bug.

**Comment by buremba** [comment]
if another person is created the report, you should not be able to delete it even if you have admin privilege. I think the problem here is that we should not show delete report button if the owner is not you.

**Comment by sambitdixit** [comment]
Yes thats right.

**Comment by buremba** [comment]
Fixed

**Comment by sambitdixit** [comment]
@buremba I'm still seeing the delete option. Can you please let me know what exactly the fix you have put so that i can test accordingly.

**Comment by buremba** [comment]
I put an indicator to the report playground page that indicates the owner of the project. You should not see the delete report button if you're not the owner of that report. Please be sure that you upgraded the latest version.

**Comment by sambitdixit** [comment]
This is still not working as expected. Attaching screenshots. 

<img width="1055" alt="screen shot 2017-06-14 at 11 04 34 am" src="https://user-images.githubusercontent.com/1338801/27116943-97672c36-50f1-11e7-8d79-549dcc49a46b.png">
<img width="1140" alt="screen shot 2017-06-14 at 11 05 01 am" src="https://user-images.githubusercontent.com/1338801/27116944-97c2cb9a-50f1-11e7-9df5-b33a8eb58d24.png">

**Comment by buremba** [comment]
I actually forgot that link and thought that you meant the delete report button in report playground. Now fixed in master. You should not see "delete report" button now.
