### ISSUE TITLE
Column 'count of rows' cannot be resolved in reports querybuilder with sort enabled

### ISSUE THREAD

**Issue by RameshByndoor** [rakam-io/rakam-ui#76]
Steps
Adding measure as other than count of rows , suppose count(x) and selecting the same x in group by. Now adding sort by x would still result in sort by "count of rows" will yield to error in query

**Comment by buremba** [comment]
Fixed

**Comment by RameshByndoor** [comment]
Seems the issue is not fixed yet. 
<img width="1093" alt="screen shot 2017-06-13 at 12 24 58 pm" src="https://user-images.githubusercontent.com/3341964/27069665-78c5ff32-5033-11e7-994d-acfc0c557e52.png">
